### ISSUE TITLE
Provided alternative install guide without Composer

### ISSUE THREAD

**Issue by GeeH** [laminas/documentation#3]
It's fair to say that the issue for Composer (#1074) regarding MITM is not trivial. We should provide a small section on installing without Composer for the tin-foil-hat brigade.

**Comment by settermjd** [comment]
@geeh, want to provide the initial draft? I'm happy to help you out with it.

**Comment by settermjd** [comment]
ping @geeh.

**Comment by froschdesign** [comment]
In recent years, there have been very few to no requests on this topic. Therefore, I do not see any need here and also the effort exceeds the benefit – for both sides, end users and documentation writers.
